language:
    - node_js
install:
    - npm install
    - npm install -g codecov
script:
    - npm run eslint_prepush
    - npm run cover
    - npm run report
    - codecov
os:
  - windows
  - linux
  - osx
