language:
    - node_js
    - php
node_js:
    - 10
php:
    - "7.0"
install:
    - npm install
    - npm install -g codecov
script:
    - npm run eslint_prepush
    - npm run cover
    - npm run report
    - codecov
os:
    - windows
    - linux
    - osx
