language:
    - node_js
node_js:
    - 10
install:
    - choco install php
    - npm install
    - npm install -g codecov
script:
    - npm run eslint_prepush
    - npm run cover
    - npm run report
    - codecov
os:
    - windows
    - linux
    - osx
