language:
    - node_js
node_js:
    - 10
matrix:
    include:
        - os: linux
        - os: osx
        - os: windows
          install:
              - choco install php
install:
    - npm install
    - npm install -g codecov
script:
    - php73 --version
    - php --version
    - npm run eslint_prepush
    - npm run cover
    - npm run report
    - codecov
